site_name: docs.saltbox.dev
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: docs
repo_url: https://github.com/saltyorg/docs

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      lang: en

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/sponsors/saltydk'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/ugfKXpFND8'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - attr_list
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Saltbox:
      - Basics: saltbox/basics/basics.md
      - Prerequisites: saltbox/prerequisites/prerequisites.md
      - Install Types: saltbox/basics/install_types.md
      - Install: saltbox/install/install.md
      - Update: saltbox/basics/update.md
      - Accessing Apps: saltbox/basics/accessing_apps.md
      - Paths: saltbox/basics/paths.md
      - Inventory: saltbox/inventory/index.md
      - Backup/Restore:
        - Settings: saltbox/backup/settings.md
        - Backup: saltbox/backup/backup.md
        - Restore: saltbox/backup/restore.md
  - Community:
      - Basics: community/basics.md
        - Apps:
          - airdcpp: community/apps/airdcpp.md
          - airsonic: community/apps/airsonic.md
          - alltube: community/apps/alltube.md
          - alternatrr: community/apps/alternatrr.md
          - alternatrrx: community/apps/alternatrrx.md
          - apprise: community/apps/apprise.md
          - archivebox: community/apps/archivebox.md
          - asshama: community/apps/asshama.md
          - autoscan: community/apps/autoscan.md
          - bazarr: community/apps/bazarr.md
          - beets: community/apps/beets.md
          - booksonic: community/apps/booksonic.md
          - bookstack: community/apps/bookstack.md
          - btrfsmaintenance: community/apps/btrfsmaintenance.md
          - calibre: community/apps/calibre.md
          - calibre_web: community/apps/calibre_web.md
          - coder: community/apps/coder.md
          - comicstreamer: community/apps/comicstreamer.md
          - comixed: community/apps/comixed.md
          - couchpotato: community/apps/couchpotato.md
          - deemix: community/apps/deemix.md
          - deluge: community/apps/deluge.md
          - delugevpn: community/apps/delugevpn.md
          - delugex: community/apps/delugex.md
          - dozzle: community/apps/dozzle.md
          - embystat: community/apps/embystat.md
          - epms: community/apps/epms.md
          - filebot: community/apps/filebot.md
          - filebrowser: community/apps/filebrowser.md
          - filezilla: community/apps/filezilla.md
          - flaresolverr: community/apps/flaresolverr.md
          - funkwhale: community/apps/funkwhale.md
          - gitea: community/apps/gitea.md
          - glances_web: community/apps/glances_web.md
          - goaccess: community/apps/goaccess.md
          - goplaxt: community/apps/goplaxt.md
          - gotify: community/apps/gotify.md
          - grafana: community/apps/grafana.md
          - guacamole: community/apps/guacamole.md
          - handbrake: community/apps/handbrake.md
          - healthchecks: community/apps/healthchecks.md
          - heimdall: community/apps/heimdall.md
          - hetzner_nfs: community/apps/hetzner_nfs.md
          - influxdb: community/apps/influxdb.md
          - invoiceninja: community/apps/invoiceninja.md
          - jellyfin: community/apps/jellyfin.md
          - jirafeau: community/apps/jirafeau.md
          - kavita: community/apps/kavita.md
          - kcptun_client: community/apps/kcptun_client.md
          - kcptun_server: community/apps/kcptun_server.md
          - kitana: community/apps/kitana.md
          - komga: community/apps/komga.md
          - lazylibrarian: community/apps/lazylibrarian.md
          - lidarrx: community/apps/lidarrx.md
          - logarr: community/apps/logarr.md
          - mediabutler: community/apps/mediabutler.md
          - medusa: community/apps/medusa.md
          - monitorr: community/apps/monitorr.md
          - moviematch: community/apps/moviematch.md
          - mylar3: community/apps/mylar3.md
          - navidrome: community/apps/navidrome.md
          - nextcloud: community/apps/nextcloud.md
          - ombi: community/apps/ombi.md
          - ombix: community/apps/ombix.md
          - ouroboros: community/apps/ouroboros.md
          - jdownloader2: community/apps/jdownloader2.md
          - petio: community/apps/petio.md
          - prowlarr: community/apps/prowlarr.md
          - qbittorrent: community/apps/qbittorrent.md
          - qbittorrentvpn: community/apps/qbittorrentvpn.md
          - qbittorrentx: community/apps/qbittorrentx.md
          - radarrx: community/apps/radarrx.md
          - readarr: community/apps/readarr.md
          - readarrx: community/apps/readarrx.md
          - requestrr: community/apps/requestrr.md
          - requestrrx: community/apps/requestrrx.md
          - resilio_sync: community/apps/resilio_sync.md
          - rflood: community/apps/rflood.md
          - rfloodx: community/apps/rfloodx.md
          - sickchill: community/apps/sickchill.md
          - sonarrx: community/apps/sonarrx.md
          - speedtest: community/apps/speedtest.md
          - sshwifty: community/apps/sshwifty.md
          - stash: community/apps/stash.md
          - synclounge: community/apps/synclounge.md
          - tautullix: community/apps/tautullix.md
          - telegraf: community/apps/telegraf.md
          - transfer: community/apps/transfer.md
          - transmission: community/apps/transmission.md
          - transmissionvpn: community/apps/transmissionvpn.md
          - transmissionx: community/apps/transmissionx.md
          - ubooquity: community/apps/ubooquity.md
          - unifi: community/apps/unifi.md
          - unmanic: community/apps/unmanic.md
          - uptime_kuma: community/apps/uptime_kuma.md
          - varken: community/apps/varken.md
          - vaultwarden: community/apps/vaultwarden.md
          - watchtower: community/apps/watchtower.md
          - wordpress: community/apps/wordpress.md
          - xteve: community/apps/xteve.md
        - Guides:
          - General:
            - chazlarson Guides: community/guides/chazguides.md
          - Linux:
            - aliases: community/guides/aliases.md
          - Plex:
            - Tautulii Custom Scripts: community/guides/tautuliscripts.md
          - Downloading:
            - Hardlinking: community/guides/hardlinking.md
        - Further Reading and Links:
          - Trashguides: community/guides/trashguides.md
          - Servarr: community/guides/servarr.md
  - Apps:
      - cloudplow: apps/cloudplow.md
      - emby: apps/emby.md
      - jackett: apps/jackett.md
      - lidarr: apps/lidarr.md
      - nzbget: apps/nzbget.md
      - nzbhydra2: apps/nzbhydra2.md
      - organizr: apps/organizr.md
      - overseerr: apps/overseerr.md
      - plex: apps/plex.md
      - portainer: apps/portainer.md
      - radarr: apps/radarr.md
      - rutorrent: apps/rutorrent.md
      - sabnzbd: apps/sabnzbd.md
      - sonarr: apps/sonarr.md
      - sstv: apps/sstv.md
      - tautulli: apps/tautulli.md
  - FAQ: faq/faq.md
  - Advanced:
      - Index: advanced/index.md
      - Adding Your Own Containers: advanced/your-own-containers.md
  - Reference:
      - Prerequisites:
          - Server: reference/server.md
          - Domain Name: reference/domain.md
          - Cloud Storage: reference/cloud.md
          - Plex Account: reference/plex.md
          - Media Sources: reference/usenet-torrent.md
      - Install:
          - Dependencies: reference/dependencies.md
          - Accounts and Settings: reference/accounts.md
          - Preinstall: reference/preinstall.md
          - Rclone: reference/rclone.md
          - Install: reference/install.md
      - Other:
          - Cloudplow Examples: reference/cloudplow.md
          - Plex Auth Token: reference/plex_auth_token.md
          - Ports: reference/ports.md
          - Pushover: reference/pushover.md

copyright: Copyright &copy; 2021 Saltbox
