site_name: docs.saltbox.dev
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: docs
repo_url: https://github.com/saltyorg/docs

edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: material/sofa
    repo: fontawesome/brands/github-alt
  custom_dir: overrides
  features:
    - content.code.copy
    - content.action.edit
    - content.action.view
    - header.autohide
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - navigation.prune
    # - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

plugins:
  - search:
      lang: en
  - meta

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    class: md-social__link heart
    link: 'https://github.com/sponsors/saltydk'
    name: Donate
  - icon: fontawesome/brands/discord
    class: md-social__link
    link: 'https://discord.gg/ugfKXpFND8'
    name: Discord
  - icon: fontawesome/brands/github
    class: md-social__link
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.tilde
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Saltbox:
      - Basics: saltbox/basics/basics.md
      - Prerequisites: saltbox/prerequisites/prerequisites.md
      - Install Types: saltbox/basics/install_types.md
      - Install: saltbox/install/install.md
      - After-Install: saltbox/install/after.md
      - Update: saltbox/basics/update.md
      - Accessing Apps: saltbox/basics/accessing_apps.md
      - Paths: saltbox/basics/paths.md
      - Inventory: saltbox/inventory/index.md
      - Backup/Restore:
        - Settings: saltbox/backup/settings.md
        - Backup: saltbox/backup/backup.md
        - Restore: saltbox/backup/restore.md
        - Migrate: saltbox/backup/migrate.md

  - Sandbox:
      - Basics: sandbox/basics.md
      - Settings: sandbox/settings.md
      - Index: sandbox/index.md
      - Apps:
        - Multiple Instances (legacy): sandbox/apps/arrx.md
        - General:
          - AdGuard Home: sandbox/apps/adguardhome.md
          - Cherry: sandbox/apps/cherry.md
          - Homebox: sandbox/apps/homebox.md
          - Joplin: sandbox/apps/joplin.md
          - Linkding: sandbox/apps/linkding.md
          - Miniflux: sandbox/apps/miniflux.md
          - Nabarr: sandbox/apps/nabarr.md
          - Notifiarr: sandbox/apps/notifiarr.md
          - Photoprism: sandbox/apps/photoprism.md
          - Recyclarr: sandbox/apps/recyclarr.md
          - Resilio Sync: sandbox/apps/resiliosync.md
          - The Lounge: sandbox/apps/thelounge.md
          - Trilium Notes: sandbox/apps/trilium.md
          - Wrapperr: sandbox/apps/wrapperr.md
          - ZNC: sandbox/apps/znc.md
        - Content Management:
          - Tandoor Recipes: sandbox/apps/tandoor.md
          - Wordpress: sandbox/apps/wordpress.md
        - Development:
          - Changedetection: sandbox/apps/changedetection.md
          - Code-server: sandbox/apps/code_server.md
          - Gitea: sandbox/apps/gitea.md
          - Gotenberg: sandbox/apps/gotenberg.md
          - Docker:
            - Dozzle: sandbox/apps/dozzle.md
            - Yacht: sandbox/apps/yacht.md
          - Mcrouter: sandbox/apps/mcrouter.md
          - OliveTin: sandbox/apps/olivetin.md
          - Reposilite: sandbox/apps/reposilite.md
          - Tika: sandbox/apps/tika.md
        - Downloading:
          - AirDC++: sandbox/apps/airdcpp.md
          - Alltube: sandbox/apps/alltube.md
          - Archivebox: sandbox/apps/archivebox.md
          - Jdownloader2: sandbox/apps/jdownloader2.md
          - Medusa: sandbox/apps/medusa.md
          - PyLoad: sandbox/apps/pyload.md
          - Rdt-client: sandbox/apps/rdtclient.md
          - Resilio Sync: sandbox/apps/resiliosync.md
          - Tubearchivist: sandbox/apps/tubearchivist.md
          - Torrents:
            - Autobrr: sandbox/apps/autobrr.md
            - Delugevpn: sandbox/apps/delugevpn.md
            - Omegabrr: sandbox/apps/omegabrr.md
            - QBit Management: sandbox/apps/qbit_manage.md
            - QBittorrentVPN: sandbox/apps/qbittorrentvpn.md
            - Rflood: sandbox/apps/rflood.md
            - Rfloodx: sandbox/apps/rfloodx.md
            - Tqm: sandbox/apps/tqm.md
            - Trackarr: sandbox/apps/trackarr.md
            - Transmission: sandbox/apps/transmission.md
            - Transmission VPN: sandbox/apps/transmissionvpn.md
            - Transmissionx: sandbox/apps/transmissionx.md
        - File Management:
          - Filebot: sandbox/apps/filebot.md
          - Filebrowser: sandbox/apps/filebrowser.md
          - Filezilla: sandbox/apps/filezilla.md
          - Jirafeau: sandbox/apps/jirafeau.md
          - Paperless-NGX: sandbox/apps/paperless-ngx.md
          - PrivateBin: sandbox/apps/privatebin.md
          - XBackBone: sandbox/apps/xbackbone.md
        - Landing Pages:
          - VNStat: sandbox/apps/vnstat.md
          - Heimdall: sandbox/apps/heimdall.md
          - Homarr: sandbox/apps/homarr.md
          - Homepage: sandbox/apps/homepage.md
        - Game Servers:
          - Minecraft: sandbox/apps/minecraft.md
          - Minecraft Bedrock: sandbox/apps/minecraft-bedrock.md
        - Media Management:
          - Books:
            - Audiobookshelf: sandbox/apps/audiobookshelf.md
            - Booksonic: sandbox/apps/booksonic.md
            - Bookstack: sandbox/apps/bookstack.md
            - Calibre: sandbox/apps/calibre.md
            - Calibre_web: sandbox/apps/calibre_web.md
            - Comicstreamer: sandbox/apps/comicstreamer.md
            - Comixed: sandbox/apps/comixed.md
            - Kavita: sandbox/apps/kavita.md
            - Komga: sandbox/apps/komga.md
            - Lazylibrarian: sandbox/apps/lazylibrarian.md
            - Mylar3: sandbox/apps/mylar3.md
            - Wikijs: sandbox/apps/wikijs.md
          # - Indexers:
          - Metadata Management:
            - Alternatrr: sandbox/apps/alternatrr.md
            - Alternatrrx: sandbox/apps/alternatrrx.md
            - MKVToolNix: sandbox/apps/mkvtoolnix.md
            - Plex Meta Manager: sandbox/apps/plex-meta-manager.md
            - Plex-utills: sandbox/apps/plex-utills.md
            - Python-plexlibrary: sandbox/apps/python-plexlibrary.md
            - Unmanic: sandbox/apps/unmanic.md
          # - Movies:
          - Music:
            - Airsonic: sandbox/apps/airsonic.md
            - Beets: sandbox/apps/beets.md
            - Deemix: sandbox/apps/deemix.md
            - Funkwhale: sandbox/apps/funkwhale.md
            - Navidrome: sandbox/apps/navidrome.md
          - TV:
            - Xteve: sandbox/apps/xteve.md
        - Media Servers and add-ons:
          - Embystat: sandbox/apps/embystat.md
          - Plex:
            - Extended Personal Media Scanner: sandbox/apps/epms.md
            - Gaps: sandbox/apps/gaps.md
            - Goplaxt: sandbox/apps/goplaxt.md
            - Kitana: sandbox/apps/kitana.md
            - Membarr: sandbox/apps/membarr.md
            - Plex Auto Languages: sandbox/apps/plex_auto_languages.md
            - Plex Autoscan: sandbox/apps/plex_autoscan.md
            - plex_dupefinder: sandbox/apps/plex_dupefinder.md
            - Plex Patrol: sandbox/apps/plex_patrol.md
            - PlexTraktSync: sandbox/apps/plextraktsync.md
            - Plex_Utills: sandbox/apps/plex_utills.md
            - Wrapperr: sandbox/apps/wrapperr.md
            - Wizarr: sandbox/apps/wizarr.md
          - Requests:
            - Doplarr: sandbox/apps/doplarr.md
            - Ombi: sandbox/apps/ombi.md
            - Ombix: sandbox/apps/ombix.md
            - Requestrr: sandbox/apps/requestrr.md
            - Requestrrx: sandbox/apps/requestrrx.md
          - Stash: sandbox/apps/stash.md
          - Whisparr: sandbox/apps/whisparr.md
        - Nextcloud: sandbox/apps/nextcloud.md
        - Social:
          - Gotify: sandbox/apps/gotify.md
          - Moviematch: sandbox/apps/moviematch.md
          - RocketChat: sandbox/apps/rocketchat.md
          - Teamspeak: sandbox/apps/teamspeak.md
        - Utilities:
          - A-Train: sandbox/apps/a_train.md
          - Database Management:
            - Adminer: sandbox/apps/adminer.md
            - PGAdmin: sandbox/apps/pgadmin.md
          - Docker:
            - Ouroboros: sandbox/apps/ouroboros.md
            - Watchtower: sandbox/apps/watchtower.md
          - Flaresolverr: sandbox/apps/flaresolverr.md
          - FreshRSS: sandbox/apps/freshrss.md
          - Gluetun: sandbox/apps/gluetun.md
          - Grafana: sandbox/apps/grafana.md
          - Guacamole: sandbox/apps/guacamole.md
          - Handbrake: sandbox/apps/handbrake.md
          - Influxdb: sandbox/apps/influxdb.md
          - Invoice Ninja: sandbox/apps/invoiceninja.md
          - Log Management:
            - GoAccess: sandbox/apps/goaccess.md
            - Logarr: sandbox/apps/logarr.md
            - Monitorr: sandbox/apps/monitorr.md
          - Networking:
            - Kcptun_client: sandbox/apps/kcptun_client.md
            - Kcptun_server: sandbox/apps/kcptun_server.md
            - Unifi: sandbox/apps/unifi.md
            - Wireguard: sandbox/apps/wireguard.md
          - MakeMKV: sandbox/apps/makemkv.md
          - Puddletag: sandbox/apps/puddletag.md
          - Sabthrottle: sandbox/apps/sabthrottle.md
          - Sarotate: sandbox/apps/sarotate.md
          - Speedtest: sandbox/apps/speedtest.md
          - Sqlitebrowser: sandbox/apps/sqlitebrowser.md
          - Sshwifty: sandbox/apps/sshwifty.md
          - Tdarr: sandbox/apps/tdarr.md
          - Tdarr Node: sandbox/apps/tdarr_node.md
          - System:
            - Apprise: sandbox/apps/apprise.md
            - Glances_web: sandbox/apps/glances_web.md
            - Healthchecks: sandbox/apps/healthchecks.md
            - Duplicati: sandbox/apps/duplicati.md
          - SyncThing: sandbox/apps/syncthing.md
          - Telegraf: sandbox/apps/telegraf.md
          - Traefik-Robotstxt: sandbox/apps/traefik_robotstxt.md
          - Unpackerr: sandbox/apps/unpackerr.md
          - Uptime Kuma: sandbox/apps/uptime_kuma.md
          - Vaultwarden: sandbox/apps/vaultwarden.md
          - Varken: sandbox/apps/varken.md

  - Apps:
      - Core [set up in this order]:
        - Nzbget: apps/nzbget.md
        - Rutorrent: apps/rutorrent.md
        - Nzbhydra2: apps/nzbhydra2.md
        - Jackett: apps/jackett.md
        - Plex: apps/plex.md
        - Autoscan: apps/autoscan.md
        - Sonarr: apps/sonarr.md
        - Radarr: apps/radarr.md
        - Lidarr: apps/lidarr.md
        - Tautulli: apps/tautulli.md
        - Overseerr: apps/overseerr.md
        - Portainer: apps/portainer.md
      - Other Media Servers:
        - Emby: apps/emby.md
        - Jellyfin: apps/jellyfin.md
      - Alternatives to Core Apps:
        - Petio: apps/petio.md
        - Plex Autoscan: apps/plex-autoscan.md
        - Prowlarr: apps/prowlarr.md
        - Sabnzbd: apps/sabnzbd.md
        - Deluge: apps/deluge.md
        - Qbittorrent: apps/qbittorrent.md
      - Others:
        - Cloudplow: apps/cloudplow.md
        - Bazarr: apps/bazarr.md
        - BTRFS Maintenance: apps/btrfsmaintenance.md
        - Hetzner NFS: apps/hetzner_nfs.md
        - Netdata: apps/netdata.md
        - Transfer: apps/transfer.md
        - Readarr: apps/readarr.md
        - asshama: apps/asshama.md
      - Support Apps:
        - diun: apps/diun.md
        - MariaDB: apps/mariadb.md
        - PostgreSQL: apps/postgres.md
      - Visualization:
        - Grafana: apps/grafana.md
      - TODO - NEED UPDATING:
        - Organizr: apps/organizr.md

  - FAQ:
      - System: faq/System.md
      - Cloud Storage: faq/Cloud Storage.md
      - CloudFlare: faq/Cloudflare.md
      - Cloudplow: faq/Cloudplow.md
      - Docker: faq/Docker.md
      - Hetzner & Google IPv6: faq/Hetzner.md
      - Install: faq/Install.md
      - Backup and Restore: faq/Backup and Restore.md
      - Rclone: faq/Rclone.md
      - Plex: faq/Plex.md
      - Plex Autoscan: faq/Plex-Autoscan.md
      - ruTorrent: faq/ruTorrent.md
      - Misc: faq/Misc.md

  - Advanced:
      - Index: advanced/index.md
      - Adding Your Own Containers: advanced/your-own-containers.md
      - Container Healthchecks: advanced/healthchecks.md
      - Styled Error Pages: advanced/styled-error-pages.md
      - Themepark Styles for apps: advanced/themepark.md
      - User crontab examples: advanced/user-crontab-examples.md
      - Feeder Mount: advanced/feeder.md

  - Reference:
      - Guides:
        - General:
          - Chazlarson Guides:
              - Can I run Saltbox on this server?: reference/guides/chazguides/server.md
              - Did my Saltbox install succeed?: reference/guides/chazguides/success.md
              - How do I mount a teamdrive?: reference/guides/chazguides/teamdrive.md
              - I can't see my media!: reference/guides/chazguides/no-media.md
              - I want some app to load at my base domain: reference/guides/chazguides/base-domain.md
              - Why is my disk full?: reference/guides/chazguides/disk-full.md
              - Installing Saltbox on a home server: reference/guides/chazguides/home-server.md
              - Obsolete and deprecated:
                - Tip 44 Guide to Shared Drive/Service Account setup for Saltbox: reference/guides/chazguides/tip44.md
                - Plex Autoscan Mappings; how do they work?: reference/guides/chazguides/pas-map.md
        - Linux:
          - Aliases: reference/guides/aliases.md
          - code-server for easier file editing: reference/guides/code-server-setup.md
        - Plex:
          - Tautulii Custom Scripts: reference/guides/tautuliscripts.md
        - Downloading:
          - Hardlinking: reference/guides/hardlinking.md
        - Google:
          - Creating a Shared Drive: reference/guides/google-shared-drive.md
        - Rclone:
          - Creating a remote: reference/guides/rclone-remote.md
          - SAFire: reference/safire.md
        - Migration:
          - Cloudbox: reference/guides/cloudbox.md
          - Plexguide: reference/guides/plexguide.md
        - Further Reading and Links:
          - Suggested Reading: reference/guides/suggested_reading.md
          - Links: reference/guides/links.md

      - Topics:
        - Prerequisite References:
          - Server: reference/server.md
          - Domain Name: reference/domain.md
          - Cloud Storage: reference/cloud.md
          - Plex Account: reference/plex.md
          - Media Sources: reference/usenet-torrent.md
        - Install References:
          - Dependencies: reference/dependencies.md
          - Accounts and Settings: reference/accounts.md
          - Preinstall: reference/preinstall.md
          - Rclone: reference/rclone.md
          # - Rclone [Auto]: reference/rclone-auto.md
          - Rclone [Manual]: reference/rclone-manual.md
          - Install: reference/install.md
        - Google References:
          - Google Permissions: reference/google-account-perms.md
          - Google Project: reference/google-project-setup.md
          - Google Group: reference/google-group-setup.md
          - Google SDK: reference/google-gcloud-tools-install.md
          - Google Service Accounts: reference/google-service-accounts.md
          - Google Shared Drives: reference/google-shared-drives.md
        - Application References:
          - Removing apps: reference/guides/app-remove.md
          - Resetting apps: reference/guides/app-reset.md
          - Updating apps: reference/guides/app-update.md
        - Other References:
          - Saltbox vs Cloudbox: reference/saltbox-vs-cloudbox.md
          - Cloudplow Examples: reference/cloudplow.md
          - Customizing Plex Libraries: reference/customizing-plex-libs.md
          - Viewing Logs: reference/logs.md
          - Multiple App Instances: reference/multiple-instances.md
          - Shared-Drive Cloudplow Setup: reference/cloudplow-config.md
          - Shared-Drive Plex Autoscan Setup: reference/plex-autoscan-config.md
          - Plex Auth Token: reference/plex_auth_token.md
          - Plex Autoscan Extras: reference/plex-autoscan-extras.md
          - Ports: reference/ports.md
          - Saltbox Tools: reference/saltbox-tools.md
          - Adding a Subdomain: reference/subdomain.md
          - Using Local Storage: reference/local-storage.md
