site_name: docs.saltbox.dev
site_url: https://docs.saltbox.dev/
site_author: salty
site_description: Saltbox is an Ansible-based solution for rapidly deploying a Docker containerized cloud media server.

repo_name: docs
repo_url: https://github.com/saltyorg/docs

edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.instant
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      lang: en

extra:
  generator: false
  social:
  - icon: fontawesome/solid/heart
    link: 'https://github.com/sponsors/saltydk'
    name: Donate
  - icon: fontawesome/brands/discord
    link: 'https://discord.gg/ugfKXpFND8'
    name: Discord
  - icon: fontawesome/brands/github
    link: 'https://github.com/saltyorg/Saltbox'
    name: GitHub

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - Saltbox:
      - Basics: saltbox/basics/basics.md
      - Prerequisites: saltbox/prerequisites/prerequisites.md
      - Install Types: saltbox/basics/install_types.md
      - Install: saltbox/install/install.md
      - After-Install: saltbox/install/after.md
      - Update: saltbox/basics/update.md
      - Accessing Apps: saltbox/basics/accessing_apps.md
      - Paths: saltbox/basics/paths.md
      - Inventory: saltbox/inventory/index.md
      - Backup/Restore:
        - Settings: saltbox/backup/settings.md
        - Backup: saltbox/backup/backup.md
        - Restore: saltbox/backup/restore.md
  - Community:
      - Basics: community/basics.md
      - Settings: community/settings.md
      - Index: community/index.md
      - Apps:
        - Content Management:
          - Wordpress: community/apps/wordpress.md
        - Development:
          - Coder: community/apps/coder.md
          - Gitea: community/apps/gitea.md
        - Downloading:
          - Alltube: community/apps/alltube.md
          - Archivebox: community/apps/archivebox.md
          - Jdownloader2: community/apps/jdownloader2.md
          - Medusa: community/apps/medusa.md
          - Torrents:
            - Deluge: community/apps/deluge.md
            - Delugevpn: community/apps/delugevpn.md
            - Delugex: community/apps/delugex.md
            - Qbittorrent: community/apps/qbittorrent.md
            - Qbittorrentvpn: community/apps/qbittorrentvpn.md
            - Qbittorrentx: community/apps/qbittorrentx.md
            - Rflood: community/apps/rflood.md
            - Rfloodx: community/apps/rfloodx.md
            - Transmission: community/apps/transmission.md
            - Transmissionvpn: community/apps/transmissionvpn.md
            - Transmissionx: community/apps/transmissionx.md
        - File Management:
          - Filebot: community/apps/filebot.md
          - Filebrowser: community/apps/filebrowser.md
          - Filezilla: community/apps/filezilla.md
          - Jirafeau: community/apps/jirafeau.md
          - Resilio_sync: community/apps/resilio_sync.md
          - Transfer: community/apps/transfer.md
        - Landing Pages:
          - heimdall: community/apps/heimdall.md
        - Media Management:
          - ArrX: community/apps/arrx.md
          - Books:
            - booksonic: community/apps/booksonic.md
            - bookstack: community/apps/bookstack.md
            - calibre: community/apps/calibre.md
            - calibre_web: community/apps/calibre_web.md
            - comicstreamer: community/apps/comicstreamer.md
            - kavita: community/apps/kavita.md
            - komga: community/apps/komga.md
            - lazylibrarian: community/apps/lazylibrarian.md
            - mylar3: community/apps/mylar3.md
            - readarr: community/apps/readarr.md
            - readarrx: community/apps/readarrx.md
            - ubooquity: community/apps/ubooquity.md
          - Indexers:
            - prowlarr: community/apps/prowlarr.md
          - Metadata Management:
            - alternatrr: community/apps/alternatrr.md
            - alternatrrx: community/apps/alternatrrx.md
            - bazarr: community/apps/bazarr.md
            - bazarrx: community/apps/bazarrx.md
            - comixed: community/apps/comixed.md
            - unmanic: community/apps/unmanic.md
          - Movies:
            - couchpotato: community/apps/couchpotato.md
            - radarrx: community/apps/radarrx.md
          - Music:
            - airsonic: community/apps/airsonic.md
            - beets: community/apps/beets.md
            - funkwhale: community/apps/funkwhale.md
            - deemix: community/apps/deemix.md
            - lidarrx: community/apps/lidarrx.md
            - navidrome: community/apps/navidrome.md
          - TV:
            - sickchill: community/apps/sickchill.md
            - sonarrx: community/apps/sonarrx.md
            - xteve: community/apps/xteve.md
        - Media Servers and add-ons:
          - Emby:
            - embystat: community/apps/embystat.md
          - jellyfin: community/apps/jellyfin.md
          - Plex:
            - asshama: community/apps/asshama.md
            - Extended Personal Media Scanner: community/apps/epms.md
            - goplaxt: community/apps/goplaxt.md
            - kitana: community/apps/kitana.md
            - mediabutler: community/apps/mediabutler.md
            - tautullix: community/apps/tautullix.md
          - Requests:
            - ombi: community/apps/ombi.md
            - ombix: community/apps/ombix.md
            - petio: community/apps/petio.md
            - requestrr: community/apps/requestrr.md
            - requestrrx: community/apps/requestrrx.md
          - stash: community/apps/stash.md
        - Nextcloud: community/apps/nextcloud.md
        - Social:
          - airdcpp: community/apps/airdcpp.md
          - gotify: community/apps/gotify.md
          - moviematch: community/apps/moviematch.md
          - synclounge: community/apps/synclounge.md
        - Utilities:
          - Docker:
            - dozzle: community/apps/dozzle.md
            - ouroboros: community/apps/ouroboros.md
            - watchtower: community/apps/watchtower.md
            - yacht: community/apps/yacht.md
          - Networking:
            - kcptun_client: community/apps/kcptun_client.md
            - kcptun_server: community/apps/kcptun_server.md
            - unifi: community/apps/unifi.md
          - flaresolverr: community/apps/flaresolverr.md
          - Log Management:
            - goaccess: community/apps/goaccess.md
            - logarr: community/apps/logarr.md
            - monitorr: community/apps/monitorr.md
          - guacamole: community/apps/guacamole.md
          - handbrake: community/apps/handbrake.md
          - influxdb: community/apps/influxdb.md
          - invoiceninja: community/apps/invoiceninja.md
          - speedtest: community/apps/speedtest.md
          - sshwifty: community/apps/sshwifty.md
          - System:
            - apprise: community/apps/apprise.md
            - autoscan: community/apps/autoscan.md
            - btrfsmaintenance: community/apps/btrfsmaintenance.md
            - glances_web: community/apps/glances_web.md
            - healthchecks: community/apps/healthchecks.md
            - hetzner_nfs: community/apps/hetzner_nfs.md
          - telegraf: community/apps/telegraf.md
          - uptime_kuma: community/apps/uptime_kuma.md
          - vaultwarden: community/apps/vaultwarden.md
          - Visualization:
            - grafana: community/apps/grafana.md
            - varken: community/apps/varken.md
      - Guides:
        - General:
          - chazlarson Guides:
              - Can I run Saltbox on this server?: community/guides/chazguides/server.md
              - Did my Saltbox install succeed?: community/guides/chazguides/success.md
              - Plex Autoscan Mappings; how do they work?: community/guides/chazguides/pas-map.md
              - How do I mount a teamdrive?: community/guides/chazguides/teamdrive.md
              - I can't see my media!: community/guides/chazguides/no-media.md
              - Tip 44 Guide to Shared Drive/Service Account setup for Saltbox: community/guides/chazguides/tip44.md
              - I want some app to load at my base domain: community/guides/chazguides/base-domain.md
              - Why is my disk full?: community/guides/chazguides/disk-full.md
              - Installing Saltbox on a home server: community/guides/chazguides/home-server.md
        - Linux:
          - aliases: community/guides/aliases.md
        - Plex:
          - Tautulii Custom Scripts: community/guides/tautuliscripts.md
        - Downloading:
          - Hardlinking: community/guides/hardlinking.md
        - Migration:
          - cloudbox: community/guides/cloudbox.md
        - Further Reading and Links:
          - Suggested Reading: community/guides/suggested_reading.md
          - Links: community/guides/links.md
  - Apps:
      - cloudplow: apps/cloudplow.md
      - emby: apps/emby.md
      - overseerr: apps/overseerr.md
      - REPLACE IMAGES:
        - jackett: apps/jackett.md
        - radarr: apps/radarr.md
        - sonarr: apps/sonarr.md
        - plex: apps/plex.md
        - lidarr: apps/lidarr.md
      - NEED UPDATING:
        - nzbget: apps/nzbget.md
        - nzbhydra2: apps/nzbhydra2.md
        - organizr: apps/organizr.md
        - portainer: apps/portainer.md
        - rutorrent: apps/rutorrent.md
        - sabnzbd: apps/sabnzbd.md
        - sstv: apps/sstv.md
        - tautulli: apps/tautulli.md
  - FAQ:
      - System: faq/System.md
      - Cloud Storage: faq/Cloud Storage.md
      - CloudFlare: faq/Cloudflare.md
      - Cloudplow: faq/Cloudplow.md
      - Docker: faq/Docker.md
      - Install: faq/Install.md
      - Backup and Restore: faq/Backup and Restore.md
      - Rclone: faq/Rclone.md
      - Plex: faq/Plex.md
      - Plex-Autoscan: faq/Plex-Autoscan.md
      - ruTorrent: faq/ruTorrent.md
      - Misc: faq/Misc.md
  - Advanced:
      - Index: advanced/index.md
      - Adding Your Own Containers: advanced/your-own-containers.md
      - User crontab examples: advanced/user-crontab-examples.md
  - Reference:
      - Prerequisites:
          - Server: reference/server.md
          - Domain Name: reference/domain.md
          - Cloud Storage: reference/cloud.md
          - Plex Account: reference/plex.md
          - Media Sources: reference/usenet-torrent.md
      - Google:
          - Google SDK: reference/google-gcloud-tools-install.md
          - Google Project: reference/google-project-setup.md
          - Google Group: reference/google-group-setup.md
          - Google Service Accounts: reference/google-service-accounts.md
          - Google Shared Drives: reference/google-shared-drives.md
      - Install:
          - Dependencies: reference/dependencies.md
          - Accounts and Settings: reference/accounts.md
          - Preinstall: reference/preinstall.md
          - Rclone: reference/rclone.md
          - Rclone [Manual]: reference/rclone-manual.md
          - Install: reference/install.md
      - Other:
          - Cloudplow Examples: reference/cloudplow.md
          - Customizing Plex Libraries: reference/customizing-plex-libs.md
          - Plex Auth Token: reference/plex_auth_token.md
          - Ports: reference/ports.md
          - Pushover: reference/pushover.md
          - Subdomains: reference/subdomain.md
  - Sandbox:
      - Basics: sandbox/basics.md
      - Settings: sandbox/settings.md
      - Index: sandbox/index.md
      - Apps:
        - General:
          - adguardhome: sandbox/apps/adguardhome.md
          - mkvtoolnix: sandbox/apps/mkvtoolnix.md
          - notifiarr: sandbox/apps/notifiarr.md
